controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

Home:
    path: /home
    controller: App\Controller\HomeController::index

Registration:
    path: /inscription
    controller: App\Controller\Registration::register